# Generated by Django 2.2.1 on 2019-05-24 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_read_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='read_num',
            new_name='views',
        ),
    ]
