# Generated by Django 2.2.1 on 2019-05-27 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190527_0222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
